### ISSUE TITLE
Can't run Redo Benchmarks

### ISSUE THREAD

**Issue by PeterTucker** [papuSpartan/stable-diffusion-webui-distributed#29]
```
DISTRIBUTED | INFO     Redoing benchmarks...                                                                                 ui.py:56
DISTRIBUTED | DEBUG    failed to load options for worker 'Pinbot-Bride-VM'                                              worker.py:684
DISTRIBUTED | DEBUG    failed to load options for worker 'Pinbot-VM'                                                    worker.py:684
Traceback (most recent call last):
  File "C:\Users\Peter\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Peter\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\Peter\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Peter\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Peter\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Peter\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Peter\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Peter\stable-diffusion-webui\extensions\stable-diffusion-webui-distributed\scripts\spartan\ui.py", line 57, in benchmark_btn
    self.world.benchmark(rebenchmark=True)
  File "C:\Users\Peter\stable-diffusion-webui\extensions\stable-diffusion-webui-distributed\scripts\spartan\world.py", line 243, in benchmark
    if worker.response.status_code != 200:
AttributeError: 'NoneType' object has no attribute 'status_code'
```

**Comment by papuSpartan** [comment]
I noticed this one after pushing the most recent release unfortunately. If you check the console logs for your workers one of them will most likely show that it couldn't find the model/checkpoint you were trying to load. Double check that you've synced all the models you want to use.

**Comment by PeterTucker** [comment]
That was it. I can generate images now, however I seems to be getting a new error in my console now:
```
DISTRIBUTED | DEBUG    world was already initialized                                                    world.py:387
DISTRIBUTED | DEBUG    added job for worker master                                                      world.py:378
DISTRIBUTED | DEBUG    added job for worker Pinbot-VM                                                   world.py:378
DISTRIBUTED | DEBUG    added job for worker Pinbot-Bride-VM                                             world.py:378
DISTRIBUTED | DEBUG    The requested number of images(1) was not cleanly divisible by the number of     world.py:472
                       realtime nodes(3) resulting in 1 that will be redistributed
DISTRIBUTED | DEBUG    There's 14.76s of slack time available for worker 'Pinbot-VM'                    world.py:515
DISTRIBUTED | DEBUG    worker 'Pinbot-VM's last ETA was off by 1.15%                                   worker.py:269
DISTRIBUTED | DEBUG    correcting 'Pinbot-VM's ETA: 11.35s -> 10.20s                                   worker.py:276
DISTRIBUTED | DEBUG    worker 'Pinbot-VM':                                                              world.py:520
                       1 complementary image(s) = 14.76s slack ÷ 10.20s per requested image
DISTRIBUTED | DEBUG    There's 14.76s of slack time available for worker 'Pinbot-Bride-VM'              world.py:515
DISTRIBUTED | DEBUG    worker 'Pinbot-Bride-VM':                                                        world.py:520
                       0 complementary image(s) = 14.76s slack ÷ 46.12s per requested image
DISTRIBUTED | INFO     Job distribution:                                                                world.py:559
                       1 * 1 iteration(s) + 1 complementary: 2 images total
                       'master' - 1 image(s) @ 9.21 ipm
                       'Pinbot-VM' - 1 image(s) @ 9.54 ipm
                       'Pinbot-Bride-VM' - 0 image(s) @ 2.35 ipm

DISTRIBUTED | DEBUG    'Pinbot-VM' job's given starting seed is 1110454593 with 1 coming before   distributed.py:325
                       it
DISTRIBUTED | DEBUG    worker 'Pinbot-VM's last ETA was off by 1.15%                                   worker.py:269
DISTRIBUTED | DEBUG    correcting 'Pinbot-VM's ETA: 11.35s -> 10.20s                                   worker.py:276
DISTRIBUTED | DEBUG    worker 'Pinbot-VM' predicts it will take 10.199s to generate 1 image(s) at a    worker.py:339
                       speed of 9.54 ipm

DISTRIBUTED | DEBUG    local script(s): [Hypertile], [ReActor], [Comments] seem to be unsupported by   worker.py:395
                       worker 'Pinbot-VM'

DISTRIBUTED | DEBUG    had to substitute sampler index with name                                       worker.py:426
100%|██████████████████████████████████████████████████████████████████████████████| 26/26 [00:08<00:00,  3.01it/s]
DISTRIBUTED | DEBUG    Took master 9.15s                                                          distributed.py:149
DISTRIBUTED | DEBUG    waiting for worker thread 'Pinbot-VM_request'                              distributed.py:154
DISTRIBUTED | DEBUG    Worker 'Pinbot-VM's ETA was off by -0.28%                                       worker.py:478
                       Predicted 10.20s. Actual: 10.23s

DISTRIBUTED | DEBUG    all worker request threads returned                                        distributed.py:157
DISTRIBUTED | DEBUG    image 2/1, info-index: 0                                                   distributed.py:120
*** Error running postprocess: C:\Users\Peter\stable-diffusion-webui\extensions\stable-diffusion-webui-distributed\scripts\distributed.py
    Traceback (most recent call last):
      File "C:\Users\Peter\stable-diffusion-webui\modules\scripts.py", line 857, in postprocess
        script.postprocess(p, processed, *script_args)
      File "C:\Users\Peter\stable-diffusion-webui\extensions\stable-diffusion-webui-distributed\scripts\distributed.py", line 357, in postprocess
        self.add_to_gallery(p=p, processed=processed)
      File "C:\Users\Peter\stable-diffusion-webui\extensions\stable-diffusion-webui-distributed\scripts\distributed.py", line 201, in add_to_gallery
        grid = images.image_grid(processed.images, len(processed.images))
    AttributeError: 'list' object has no attribute 'image_grid'
---
```

**Comment by PeterTucker** [comment]
Figured it out. I'm guessing because it's distributed the Gallery Grid image does not get generated. You can turn off the gallery grid image in settings:
![image](https://github.com/papuSpartan/stable-diffusion-webui-distributed/assets/1381341/698b66e2-9a66-4030-a83e-9c7e1f361015)

**Comment by papuSpartan** [comment]
It's good that you were able to get around it but no it should work with grid on as well. I'll take a look at it sometime soon. Let me know what commit of sdwui you're on.

**Comment by PeterTucker** [comment]
version: [v1.9.3](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/1c0a0c4c26f78c32095ebc7f8af82f5c04fca8c0)  •  python: 3.10.6  •  torch: 2.1.2+cu121  •  xformers: 0.0.23.post1  •  gradio: 3.41.2  •  checkpoint: [c9e3e68f89](https://google.com/search?q=c9e3e68f89b8e38689e1097d4be4573cf308de4e3fd044c64ca697bdb4aa8bca)

![image](https://github.com/papuSpartan/stable-diffusion-webui-distributed/assets/1381341/ad8f6898-89e6-4816-a85c-048d55becddd)

**Comment by PeterTucker** [comment]
Is there anyway to use Distributed with other plugins, specifically Reactor? https://github.com/Gourieff/sd-webui-reactor

**Comment by papuSpartan** [comment]
Can you see if the latest update I just pushed, [2.2.1](https://github.com/papuSpartan/stable-diffusion-webui-distributed/releases/tag/v2.2.1) fixes your problems?

---

> Is there anyway to use Distributed with other plugins, specifically Reactor? https://github.com/Gourieff/sd-webui-reactor

There is but I haven't implemented a universal solution yet. It's something I'm currently looking to improve.

**Comment by PeterTucker** [comment]
Anyway I could get the workaround for Reactor? :)
