### ISSUE TITLE
can not installed this plugin

### ISSUE THREAD

**Issue by kebe7jun** [papuSpartan/stable-diffusion-webui-distributed#30]
Error log:
```
*** Error completing request
*** Arguments: ('https://github.com/papuSpartan/stable-diffusion-webui-distributed.git', ['ads', 'localization', 'installed'], 0, '') {}
    Traceback (most recent call last):
      File "/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/stable-diffusion-webui/modules/ui_extensions.py", line 397, in install_extension_from_index
        ext_table, message = install_extension_from_url(None, url)
      File "/stable-diffusion-webui/modules/ui_extensions.py", line 339, in install_extension_from_url
        check_access()
      File "/stable-diffusion-webui/modules/ui_extensions.py", line 23, in check_access
        assert not shared.cmd_opts.disable_extension_access, "extension access disabled because of command line flags"
    AssertionError: extension access disabled because of command line flags

---
```

**Comment by kebe7jun** [comment]
resolved.
